name: "AutomaticBooks"
version: "2.2.1"
api-version: "1.13"
main: com.github.devmanu.automaticbooks.AutomaticBooks
softdepend: [PlaceholderAPI, ProtocolLib]
commands:
  book:
    description: Manage books
